#!/usr/bin/env bash
# =====================================================================
# TechZone — one-shot catalogue seeder
#
# Runs in the `db-seed` container (profile: seed). It exists because the
# schema is owned by Hibernate (`ddl-auto: update`): MySQL's own
# /docker-entrypoint-initdb.d scripts run before any Spring service starts,
# when no table exists yet, so row seeding has to happen later.
#
# The script therefore waits for product-service to have created its tables,
# skips if the catalogue already has rows, applies catalogue.sql, and finally
# raises the Hibernate id generator past the seeded ids.
# =====================================================================
set -euo pipefail

MYSQL_HOST="${MYSQL_HOST:-mysql}"
MYSQL_USER="${MYSQL_USER:-root}"
PRODUCT_DB="${PRODUCT_DB:-ecommerce_product}"
USER_DB="${USER_DB:-ecommerce}"
SELLER_USERNAME="${SELLER_USERNAME:-seller1}"

# Seconds to wait for Hibernate to create the product-service schema. The
# service only starts after config-server, discovery-service and the gateway
# are healthy, so the first boot of a cold stack is genuinely slow.
WAIT_TIMEOUT="${WAIT_TIMEOUT:-300}"
WAIT_INTERVAL=5

# next_val floor for the `product_seq` table generator — comfortably above the
# highest id in catalogue.sql.
SEQ_FLOOR=1000

SEED_DIR="$(cd "$(dirname "$0")" && pwd)"

# Passing the password through MYSQL_PWD keeps the client's "using a password
# on the command line is insecure" warning out of the container logs.
export MYSQL_PWD="${MYSQL_PASSWORD:-root}"

log() { echo "[db-seed] $*"; }

# Every mysql call must pin the connection charset. The client otherwise
# negotiates latin1, and any non-ASCII byte in catalogue.sql — an em dash, a
# Vietnamese diacritic — is read as latin1 and re-encoded, landing in the
# utf8mb4 column double-encoded ("—" stored as "â€”").
MYSQL_OPTS=(--host="$MYSQL_HOST" --user="$MYSQL_USER" --default-character-set=utf8mb4)

# Scalar query: prints the single value, or nothing if the server is not up yet.
query() {
    mysql "${MYSQL_OPTS[@]}" --batch --skip-column-names --silent -e "$1" 2>/dev/null || true
}

exec_sql() {
    mysql "${MYSQL_OPTS[@]}" -e "$1"
}

table_exists() {
    query "SELECT COUNT(*) FROM information_schema.tables
           WHERE table_schema = '$1' AND table_name = '$2'"
}

# ---------------------------------------------------------------------
# 1. Wait for the schema product-service creates on first boot
# ---------------------------------------------------------------------
log "waiting for $PRODUCT_DB schema (timeout ${WAIT_TIMEOUT}s)…"
elapsed=0
while true; do
    ready="$(query "SELECT COUNT(*) FROM information_schema.tables
                    WHERE table_schema = '$PRODUCT_DB'
                      AND table_name IN ('product', 'category', 'product_specifications')")"
    if [ "$ready" = "3" ]; then
        log "schema is ready after ${elapsed}s"
        break
    fi
    if [ "$elapsed" -ge "$WAIT_TIMEOUT" ]; then
        log "ERROR: product-service has not created its tables within ${WAIT_TIMEOUT}s."
        log "       Is it running? Check: docker compose logs product-service"
        exit 1
    fi
    sleep "$WAIT_INTERVAL"
    elapsed=$((elapsed + WAIT_INTERVAL))
done

# ---------------------------------------------------------------------
# 2. Skip if there is already a catalogue
#
# This is what makes re-running the seed profile harmless, and it means the
# seed never overwrites products entered by hand.
# ---------------------------------------------------------------------
product_count="$(query "SELECT COUNT(*) FROM \`$PRODUCT_DB\`.\`product\`")"
if [ -n "$product_count" ] && [ "$product_count" != "0" ]; then
    log "catalogue already holds $product_count product(s) — nothing to do"
    exit 0
fi

# ---------------------------------------------------------------------
# 3. Resolve the seller the demo products belong to
#
# Both schemas live in this one MySQL instance, so seller1's id can be read
# back from user-service's table instead of being hard-coded — its value is
# generated by the CommandLineRunner in UserServiceConfig. If user-service has
# not seeded yet, the products are still created, just without an owner.
# ---------------------------------------------------------------------
seller_id="NULL"
seller_email="NULL"
if [ "$(table_exists "$USER_DB" "user")" = "1" ]; then
    found="$(query "SELECT user_id FROM \`$USER_DB\`.\`user\`
                    WHERE username = '$SELLER_USERNAME' LIMIT 1")"
    if [ -n "$found" ]; then
        seller_id="$found"
        seller_email="'$(query "SELECT email FROM \`$USER_DB\`.\`user\`
                                WHERE user_id = $found LIMIT 1")'"
        log "demo products will be owned by $SELLER_USERNAME (user_id=$seller_id)"
    fi
fi
if [ "$seller_id" = "NULL" ]; then
    log "WARNING: user '$SELLER_USERNAME' not found in $USER_DB — seeding products without a seller"
fi

# ---------------------------------------------------------------------
# 4. Apply the catalogue
# ---------------------------------------------------------------------
log "applying catalogue.sql…"
mysql "${MYSQL_OPTS[@]}" \
      --init-command="SET @seller_id = $seller_id, @seller_email = $seller_email;" \
      "$PRODUCT_DB" < "$SEED_DIR/catalogue.sql"

# ---------------------------------------------------------------------
# 5. Move the Hibernate id generator past the seeded ids
#
# Product.productId uses GenerationType.AUTO, which on MySQL makes Hibernate 6
# allocate ids from the `product_seq` table rather than AUTO_INCREMENT. The
# seeded rows carry explicit ids, so without this the next product created
# through the UI would collide on the primary key.
# ---------------------------------------------------------------------
if [ "$(table_exists "$PRODUCT_DB" "product_seq")" = "1" ]; then
    exec_sql "UPDATE \`$PRODUCT_DB\`.\`product_seq\`
              SET next_val = $SEQ_FLOOR WHERE next_val < $SEQ_FLOOR"
    log "product_seq raised to at least $SEQ_FLOOR"
else
    log "note: no product_seq table found — id generation left untouched"
fi

seeded="$(query "SELECT COUNT(*) FROM \`$PRODUCT_DB\`.\`product\`")"
categories="$(query "SELECT COUNT(*) FROM \`$PRODUCT_DB\`.\`category\`")"
log "done — $seeded products across $categories categories"
