spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: thaivanlam373@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
