spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laptop_ecommerce_graduation_project_order_service?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: thailam123
  rabbitmq:
    host: localhost

frontend:
  url: http://localhost:5173

product:
  service:
    base-url: http://localhost:8081/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
