spring:
  jpa:
    hibernate:
      ddl-auto: update

  app:
    jwtSecret: mySecretKey123912738fsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfgfdhrher
    jwtExpirationMs: 3000000
  ecom:
    app:
      jwtCookieName: springBootEcom

server:
  port: 8082
